### ISSUE TITLE
Test suite creates zero-initialized String

### ISSUE THREAD

**Issue by RalfJung** [Badel2/zerobuf#1]
I am working on enabling Rust to better detect misuse of uninitialized memory (https://github.com/rust-lang/rust/pull/71274), and this crate was flagged as a possible regression. Specifically, this line:

https://github.com/Badel2/zerobuf/blob/5038006fa73197cdc5ed83ff48a016b4e446b50b/src/lib.rs#L366

creates a zero-initialized `String`, which is [Undefined Behavior](https://doc.rust-lang.org/reference/behavior-considered-undefined.html) as strings must never be 0.

**Comment by Badel2** [comment]
Good find, that's true. The purpose of that test is to check if "all zeros" is a valid value of type `T`. It seems impossible to check that without undefined behavior.

But if you implement that check into the compiler that's perfect, then this library will always be safe to use as users will not be able to create a `ZeroBuf<String>` because of a compiler error.

**Comment by RalfJung** [comment]
The check in the compiler is not and never will be 100% safe. There is no way in Rust to determine if type type `T` can be zero-initialized; that would require a trait that lets crate authors inform users if their type supports something like this.

**Comment by Badel2** [comment]
That makes sense. Anyway, I released `0.0.3` with that one test removed. Thank you very much for your work!

**Comment by RalfJung** [comment]
I think the crate I had in mind is https://docs.rs/zerocopy/0.3.0/zerocopy/. It has some useful traits, though not one that exactly matches "zero-initializable".
